// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHL-K2_VAcoo7GjrCuaKplxuda0ItG6uI',
    appId: '1:368428267080:web:78bdc41584c7bd57e50a7d',
    messagingSenderId: '368428267080',
    projectId: 'handpumpking-c883d',
    authDomain: 'handpumpking-c883d.firebaseapp.com',
    storageBucket: 'handpumpking-c883d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1MqLUyDYSBC8lxwwmKDdJCmdGSFoEAbY',
    appId: '1:368428267080:android:2a93337a717ecf1fe50a7d',
    messagingSenderId: '368428267080',
    projectId: 'handpumpking-c883d',
    storageBucket: 'handpumpking-c883d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZPJZ-_9lXPJd5NoaP-0260mZ-O0KRGsU',
    appId: '1:368428267080:ios:06df4b435922e1e2e50a7d',
    messagingSenderId: '368428267080',
    projectId: 'handpumpking-c883d',
    storageBucket: 'handpumpking-c883d.appspot.com',
    iosBundleId: 'com.handpumpofficer',
  );
}
