import 'package:get/get.dart';

class Strings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'hi_IN': {
          'LOGIN': 'लॉग इन करें',
          "LOGOUT": "लॉगआउटं",
          'SIGNUP': 'साइन अप करें',
          'USERNAME_OR_EMAIL': 'उपयोगकर्ता का नाम या ईमेल',
          'PASSWORD': 'पासवर्ड',
          'FORGOT_YOUR_PASSWORD': 'अपना कूट शब्द भूल गए?',
          'PLEASE_ENTER_YOUR_EMAIL': 'अपना ईमेल दर्ज करें',
          'PLEASE_ENTER_YOUR_PASSWORD': 'कृपया अपना पासवर्ड दर्ज करें',
          'CREATE_YOUR_ACCOUNT': 'अपना खाता बनाएं',
          'FIRST_NAME': 'पहला नाम',
          'NAME': 'नाम',
          'ENTER_YOUR_NAME': 'अपना नाम दर्ज करें',
          'LAST_NAME': 'अंतिम नाम',
          'ENTER_YOUR_LAST_NAME': 'अपना अंतिम नाम दर्ज करें',
          'USER_NAME': 'उपयोगकर्ता नाम',
          'PHONE': 'फ़ोन नंबर',
          'ENTER_YOUR_PHONE': 'अपना फ़ोन नंबर दर्ज करें',
          'ADDRESS': 'पता',
          'ENTER_YOUR_ADDRESS': 'अपना पता दर्ज करें',
          'CITY': 'शहर',
          'PDF': 'पंचनामा डाउनलोड करें',
          'ENTER_CITY': 'अपना शहर दर्ज करें',
          'SUBMIT': 'सबमिट करें',
          'UPDATE': 'प्रोफ़ाइल अद्यतन करें',
          'COMPAINT_DESCRIP': 'शिकायत विवरण',
          'ENTER_YOUR_USER_NAME': 'अपना उपयोगकर्ता नाम दर्ज करें',
          'SIGNUP_AND_ACCEPT': 'साइनअप करें और स्वीकार करें',
          'BY_TAPPING_SIGNUP': "साइन अप करें और स्वीकार करें'' टैप करके, आप स्वीकार करते हैं कि आपने पढ़ लिया है",
          'PRIVACY_POLICY': 'गोपनीयता नीति',
          'AND_AGREE_TO_THE': 'और इससे सहमत हूं',
          'TERMS_OF_SERVICE': 'सेवा की शर्तें',
          'CHAT': 'चैट',
          'STORIES': 'Stories',
          'QUICK_ADD': 'Quick Add',
          'SUBSCRIPTION': 'Subscription',
          'DISCOVER': 'Discover',
          'FRIENDS': 'Friends',
          'MY_BITMOJI': 'My Bitmoji',
          'WELCOME': 'आपका स्वागत है!',
          'SIGNINAC': 'अपने खाते में साइन इन करें',
          'SIGNUPAC': 'खाता बनाएं और सभी सेवाओं का आनंद लें',
          'SERVICES': 'सेवाएं',
          'PROMOTION': 'पदोन्नति',
          'VIEWALL': 'सभी को देखें',
          'NOTIFICATIONS': 'सूचनाएं',
          'PROFILE': 'प्रोफ़ाइल',
          'COMPLAINT': 'शिकायत',
          'COMPLAINTS': 'शिकायतें',
          'MYCOMPLAINTS': 'मेरी शिकायतें',
          'UPLOAD': 'फोटो अपलोड करें',
          'PLZCHOSE': 'कृपया शिकायत स्थान के लिए स्थान का चयन करें',
          'MOREINFO': 'शिकायत के लिए अधिक जानकारी भरें -->',
          'TYPELOC': ' स्थान टाइप करें',
          'CFORM': 'शिकायत फ़ॉर्म',
          'ISSUES': 'समस्याएँ',
          'GENDER': 'लिंग',
          'SelectGENDER': 'लिंग चुनें',
          'ZONE': 'क्षेत्र',
          'ENTERZONE': 'पिनकोड दर्ज करें',
          'COUNTTRY': 'देश',
          'SELECTCATEGORY': 'श्रेणी चुनें',
          'SELECTISSUE': 'समस्याएँ चुनें:',
          'Issues': 'समस्याएँ',
          'Promotion': 'प्रमोशन',
          'Total': 'कुल शिकायतें',
          'Pending': 'लंबित',
          'In Progress': 'प्रगति पर है',
          'INProgress': 'प्रगति पर है',
          'Completed': 'शिकायतों का समाधान किया गया',
          'STATUS': 'स्थिति',
          'Complete': 'पूर्ण',
          'SELECTLOC': 'चयनित स्थान',
          'APPROVE': 'स्वीकृत',
          'REJECT': 'अस्वीकार',
          'NEXT': 'NEXT',
          'VendorList': 'सौंपी गई शिकायत सूची',
          'SelectLanguage': 'भाषा चुने',
          'Language': 'भाषा',
          'Hindi': 'हिंदी',
          'English': 'अंग्रेज़ी',
          'UsedITEM': 'प्रयुक्त उत्पाद वस्तुएँ',
          'Quantity': 'मात्रा',
          'id': 'आईडी',
          'Date': 'तारीख',
          'Due': 'देय तारीख',
          'Assign': 'के लिए आवंटित',
          'Type': 'प्रकार',
          'ServiceType': 'सेवा प्रकार',
          'Notes': 'टिप्पणियाँ',
          'Image': 'फ़ोटो',
          'View': ' देखें ',
          'MYLIST': 'मेरी प्रगतिशील शिकायत',
          'Profile': 'प्रोफ़ाइल',
          'Close': 'रद्द करें',
          'Chart': 'शिकायत चार्ट',
          'NOTFOUND': 'नहीं मिला',
          "SERVICE_TYPE": "सेवा प्रकार",
          "service_type": "सेवा प्रकार",
          "Video": "वीडियो",
          "Video not found": "वीडियो नहीं मिला",
          "CATEGORY": "वर्ग",
          "note": "टिप्पणी",
          "Download the invoice": "पंचनामा डाउनलोड करे",
          "WORKING": "प्रगती पर हे",
          "SIGNATURE": "हस्ताक्षर",
          "Signature not found": "कोई हस्ताक्षर नहीं मिले",
          "YES": "हाँ",
          "NO": "नहीं",
          "Do you want to log out?": "क्या आप लॉग आउट करना चाहते हैं?",
          "DATA NOT FOUND": "डेटा प्राप्त नहीं हुआ",
          "Please add your signature in the profile section": "कृपया प्रोफ़ाइल अनुभाग में अपना हस्ताक्षर जोड़ें",
        },
        'en_US': {
          'LOGIN': 'Log In',
          'SIGNUP': 'Sign Up',
          'USERNAME_OR_EMAIL': 'Username or Email',
          'PASSWORD': 'Password',
          'FORGOT_YOUR_PASSWORD': 'Forgot your password?',
          'PLEASE_ENTER_YOUR_EMAIL': 'Please enter your email',
          'PLEASE_ENTER_YOUR_PASSWORD': 'Please enter your password',
          'CREATE_YOUR_ACCOUNT': 'Create Your Account',
          'FIRST_NAME': 'First Name',
          'NAME': 'Name',
          'ENTER_YOUR_NAME': 'Enter your name',
          'LAST_NAME': 'Last Name',
          'ENTER_YOUR_LAST_NAME': 'Enter your last name',
          'USER_NAME': 'User Name',
          'PHONE': 'Phone Number',
          'ENTER_YOUR_PHONE': 'Enter your phone number',
          'reADDRESS': 'Address',
          'ENTER_YOUR_ADDRESS': 'Enter your address',
          'CITY': 'City',
          'PDF': 'Download PDF',
          'ENTER_CITY': 'Enter your city',
          'SUBMIT': 'Submit',
          'UPDATE': 'Update Profile',
          'COMPAINT_DESCRIP': 'Complaint Description',
          'ENTER_YOUR_USER_NAME': 'Enter your username',
          'SIGNUP_AND_ACCEPT': 'Sign up and accept',
          'BY_TAPPING_SIGNUP':
              'By tapping "Sign Up and Accept", you acknowledge that you have read',
          'PRIVACY_POLICY': 'Privacy Policy',
          'AND_AGREE_TO_THE': 'and agree to the',
          'TERMS_OF_SERVICE': 'Terms of Service',
          'CHAT': 'Chat',
          'STORIES': 'Stories',
          'QUICK_ADD': 'Quick Add',
          'SUBSCRIPTION': 'Subscription',
          'DISCOVER': 'Discover',
          'FRIENDS': 'Friends',
          'MY_BITMOJI': 'My Bitmoji',
          'WELCOME': 'Welcome!',
          'SIGNINAC': 'Sign in to your account',
          'SIGNUPAC': 'Create an account and enjoy all the services',
          'SERVICES': 'Services',
          'PROMOTION': 'Promotion',
          'VIEWALL': 'View All',
          'NOTIFICATIONS': 'Notifications',
          'PROFILE': 'Profile',
          'COMPLAINT': 'Complaint',
          'COMPLAINTS': 'Complaints',
          'MYCOMPLAINTS': 'My Complaints',
          'UPLOAD': 'Upload Photo',
          'PLZCHOSE': 'Please select a location for the complaint',
          'MOREINFO': 'Fill more information for the complaint -->',
          'TYPELOC': 'Type location',
          'CFORM': 'Complaint Form',
          'ISSUES': 'Issues',
          'GENDER': 'Gender',
          'SelectGENDER': 'Select Gender',
          'ZONE': 'Zone',
          'ENTERZONE': 'Enter Pincode',
          'COUNTTRY': 'Country',
          'SELECTCATEGORY': 'Select Category',
          'SELECTISSUE': 'Select Issues:',
          'Issues': 'Issues',
          'Promotion': 'Promotion',
          'Total': 'Total Complaints',
          'Pending': 'Pending',
          'INProgress': 'In Progress',
          'Completed': 'Completed Complaints',
          'STATUS': 'Status',
          'Complete': 'Complete',
          'SELECTLOC': 'Selected Location',
          'APPROVE': 'Approve',
          'NEXT': 'Next',
          'VendorList': 'Assigned Complaint List',
          'SelectLanguage': 'Select Language',
          'Language': 'Language',
          'Hindi': 'Hindi',
          'English': 'English',
          'UsedITEM': 'Used Item Products',
          'Quantity': 'Quantity',
          'id': 'ID',
          'Date': 'Date',
          'Due': 'Due Date',
          'Assign': 'Assigned To',
          'Type': 'Type',
          'ServiceType': 'Service Type',
          'Notes': 'Notes',
          'Image': 'Image',
          'View': 'View',
          'MYLIST': 'My Progressive Complaint',
          'Close': 'Cancel',
          'Chart': 'Complaint Chart',
          'NOTFOUND': 'Not Found',
          "LOGOUT": "LOGOUT",
        },
      };
}
